package com.customermanagementportal3.Exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestControllerAdvice
//It will handle all the exception generated by controller not by any particular method
public class GlobalExceptionHandler {
    private ObjectError e;

    //Handles the Hibernate Starter Validator
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Map<String, String>> handleMethodArgsNotValidException(MethodArgumentNotValidException ex) {
        HashMap<String, String> map = new HashMap<>();
        List<ObjectError> listOfErrors = ex.getBindingResult().getAllErrors();
        for (ObjectError e : listOfErrors) {
            String fieldName = ((FieldError) e).getField();
            String message = e.getDefaultMessage();
            map.put(fieldName, message);
        }
        return new ResponseEntity<>(map, HttpStatus.BAD_REQUEST);


    }

}
